var MESSAGE_TYPES = {
    PING: 'PING',
    GET_LAST_CONVERSION: 'GET_LAST_CONVERSION',
    GET_HISTORY: 'GET_HISTORY',
    GET_SETTINGS: 'GET_SETTINGS',
    SAVE_SETTINGS: 'SAVE_SETTINGS',
    CONVERT_ACTIVE_TAB: 'CONVERT_ACTIVE_TAB',
    DOWNLOAD_MARKDOWN: 'DOWNLOAD_MARKDOWN'
};

var ERROR_CODES = {
    NOT_EXTRACTABLE: 'NOT_EXTRACTABLE',
    PERMISSION_REQUIRED: 'PERMISSION_REQUIRED',
    CONVERSION_FAILED: 'CONVERSION_FAILED',
    UNKNOWN_MESSAGE: 'UNKNOWN_MESSAGE'
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { MESSAGE_TYPES, ERROR_CODES };
}
